# Generated by Django 5.0.9 on 2026-09-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('REQUEST_RECEIVED', 'Request Received'), ('PROVIDER_FOUND', 'Provider Found'), ('PROVIDER_ACCEPTED', 'Provider Accepted'), ('PROVIDER_ON_THE_WAY', 'Provider On The Way'), ('PROVIDER_ARRIVED', 'Provider Arrived'), ('SERVICE_COMPLETED', 'Service Completed'), ('PAYMENT_SUCCESSFUL', 'Payment Successful'), ('NEW_REQUEST', 'New Request'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('SERVICE_ASSIGNED', 'Service Assigned')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='assistance.assistancerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
    ]
