# Generated by Django 5.0.9 on 2026-09-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_type', models.CharField(choices=[('Car', 'Car'), ('Two-Wheeler', 'Two-Wheeler')], default='Car', max_length=20)),
                ('vehicle_number', models.CharField(db_index=True, max_length=20)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric')], default='Petrol', max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('is_primary', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='vehicles_ve_user_id_b027ef_idx'), models.Index(fields=['vehicle_number'], name='vehicles_ve_vehicle_f82abf_idx')],
            },
        ),
    ]
