# Generated by Django 5.0.9 on 2026-09-07 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('service_category', models.CharField(choices=[('MECHANIC', 'Mechanic'), ('PUNCTURE', 'Puncture Assistance'), ('BATTERY', 'Battery Assistance'), ('FUEL', 'Fuel Delivery'), ('TOWING', 'Towing'), ('CAR_REPAIR', 'Car Repair'), ('TWO_WHEELER_REPAIR', 'Two-Wheeler Repair'), ('SERVICE_CENTER', 'Service Center')], max_length=30)),
                ('problem_type', models.CharField(blank=True, choices=[('ENGINE_PROBLEM', 'Engine Problem'), ('STARTING_PROBLEM', 'Starting Problem'), ('OVERHEATING', 'Overheating'), ('BRAKE_PROBLEM', 'Brake Problem'), ('CLUTCH_PROBLEM', 'Clutch Problem'), ('GEAR_PROBLEM', 'Gear Problem'), ('PUNCTURE', 'Puncture'), ('FLAT_TYRE', 'Flat Tyre'), ('TYRE_REPLACEMENT', 'Tyre Replacement'), ('DEAD_BATTERY', 'Dead Battery'), ('BATTERY_REPLACEMENT', 'Battery Replacement'), ('JUMP_START', 'Jump Start'), ('OUT_OF_FUEL', 'Out of Fuel'), ('PETROL_DELIVERY', 'Petrol Delivery'), ('DIESEL_DELIVERY', 'Diesel Delivery'), ('ACCIDENT', 'Accident'), ('VEHICLE_CANNOT_MOVE', 'Vehicle Cannot Move'), ('NEED_TOWING', 'Need Towing'), ('OTHER', 'Other Problem')], max_length=30)),
                ('problem_description', models.TextField(blank=True)),
                ('problem_image', models.ImageField(blank=True, null=True, upload_to='problem_images/')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='NORMAL', max_length=10)),
                ('is_sos', models.BooleanField(default=False)),
                ('emergency_type', models.CharField(blank=True, max_length=50)),
                ('latitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(db_index=True, decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SEARCHING', 'Searching'), ('PROVIDER_ASSIGNED', 'Provider Assigned'), ('ACCEPTED', 'Accepted'), ('ON_THE_WAY', 'On The Way'), ('ARRIVED', 'Arrived'), ('REPAIRING', 'Repairing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimated_eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travel_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('parts_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('on_the_way_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, max_length=10)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_received', to='providers.providerprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer'], name='assistance__custome_c051ee_idx'), models.Index(fields=['provider'], name='assistance__provide_855928_idx'), models.Index(fields=['status'], name='assistance__status_ea20a0_idx'), models.Index(fields=['priority'], name='assistance__priorit_83bdeb_idx'), models.Index(fields=['created_at'], name='assistance__created_f95d61_idx')],
            },
        ),
    ]
